"""Trace the wave mockup into millimetre polygons — digital tracing paper.

Pipeline (no OpenCV needed; PIL + scipy.ndimage + matplotlib marching squares):
  1. classify pixels: blue plate / white gap / gray rim+gears / background
  2. the OUTER white background is the white blob touching the border;
     every OTHER white blob is an interior wave-gap (a closed shape)
  3. find the disc (everything not background): centroid = center,
     sqrt(area/pi) = radius; that circle maps to our RIM (r83)
  4. each interior gap -> ordered boundary contour (plt.contour) ->
     millimetre polygon (center-relative, Y flipped, Douglas-Peucker)
  5. write art/wave_traced.py: WAVE_POLYS the bridge subtracts as-drawn

Run: PYTHONPATH=. .venv/bin/python tools/trace_wave.py [rotate_deg]
"""
import sys
sys.setrecursionlimit(20000)

import numpy as np
from PIL import Image
from scipy import ndimage

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt

RIM = 83.0
ROT = float(sys.argv[1]) if len(sys.argv) > 1 else 0.0
MIN_AREA_PX = 450          # drop the little screw-hole dots
DP_TOL_MM = 0.35           # Douglas-Peucker simplification


def classify(rgb):
    r, g, b = rgb[..., 0], rgb[..., 1], rgb[..., 2]
    white = (r > 195) & (g > 195) & (b > 195)
    blue = (b.astype(int) - r) > 35
    return white, blue


def _dp_open(pts, tol):
    """Douglas-Peucker on an OPEN polyline (distinct endpoints)."""
    if len(pts) < 3:
        return pts
    a, b = pts[0], pts[-1]
    ab = b - a
    L = np.hypot(*ab) + 1e-9
    rel = pts - a
    d = np.abs(ab[0] * rel[:, 1] - ab[1] * rel[:, 0]) / L
    i = int(d.argmax())
    if d[i] > tol:
        left = _dp_open(pts[:i + 1], tol)
        right = _dp_open(pts[i:], tol)
        return np.vstack([left[:-1], right])
    return np.vstack([a, b])


def _dp(pts, tol):
    """Simplify a CLOSED contour: split at the point farthest from the
    start (a real diameter endpoint) so the two arcs have distinct ends,
    then DP each. A naive DP would see first==last and collapse to 2 pts."""
    if len(pts) < 5:
        return pts
    d0 = np.hypot(pts[:, 0] - pts[0, 0], pts[:, 1] - pts[0, 1])
    i = int(d0.argmax())
    a = _dp_open(pts[:i + 1], tol)
    b = _dp_open(pts[i:], tol)
    return np.vstack([a[:-1], b[:-1]])


def main():
    img = Image.open("art/wave_reference.png").convert("RGB")
    rgb = np.asarray(img)
    H, W = rgb.shape[:2]
    white, blue = classify(rgb)

    # exterior background = white blobs touching the image border
    lbl, n = ndimage.label(white)
    border = set(lbl[0, :]) | set(lbl[-1, :]) | set(lbl[:, 0]) | set(lbl[:, -1])
    border.discard(0)
    exterior = np.isin(lbl, list(border))

    disc = ~exterior                       # rim + blue + interior gaps + gears
    ys, xs = np.nonzero(disc)
    cy, cx = ys.mean(), xs.mean()
    radius_px = np.sqrt(disc.sum() / np.pi)
    scale = RIM / radius_px
    print(f"disc center=({cx:.0f},{cy:.0f}) r={radius_px:.0f}px  "
          f"scale={scale:.4f} mm/px")

    # interior gaps: white, not exterior, comfortably inside the rim
    yy, xx = np.mgrid[0:H, 0:W]
    inside = ((xx - cx) ** 2 + (yy - cy) ** 2) < (0.955 * radius_px) ** 2
    gaps = white & (~exterior) & inside
    glbl, gn = ndimage.label(gaps)
    sizes = ndimage.sum(np.ones_like(glbl), glbl, range(1, gn + 1))

    ca, sa = np.cos(np.radians(ROT)), np.sin(np.radians(ROT))

    def to_mm(col, row):
        x = (col - cx) * scale
        y = (cy - row) * scale                 # flip Y (image row grows down)
        return (x * ca - y * sa, x * sa + y * ca)

    polys = []
    for gi in range(1, gn + 1):
        if sizes[gi - 1] < MIN_AREA_PX:
            continue
        mask = (glbl == gi).astype(float)
        cs = plt.contour(mask, levels=[0.5])
        segs = [s for s in cs.allsegs[0] if len(s) >= 8]
        if not segs:
            continue
        seg = max(segs, key=len)               # the blob's outer loop
        mm = np.array([to_mm(c, r) for c, r in seg])
        mm = _dp(mm, DP_TOL_MM)
        if len(mm) >= 4:
            polys.append(mm)
    plt.close("all")
    print(f"traced {len(polys)} wave gaps "
          f"({sum(len(p) for p in polys)} points total)")

    with open("art/wave_traced.py", "w") as f:
        f.write('"""Auto-generated by tools/trace_wave.py from '
                'art/wave_reference.png.\nEdit the mockup and re-run; do not '
                'hand-edit. Millimetre polygons,\nmovement coordinates '
                '(origin=center, +Y up)."""\n\n')
        f.write(f"ROT_DEG = {ROT}\n")
        f.write("WAVE_POLYS = [\n")
        for p in polys:
            f.write("    [" + ", ".join(f"({x:.2f},{y:.2f})" for x, y in p)
                    + "],\n")
        f.write("]\n")
    print("wrote art/wave_traced.py")


if __name__ == "__main__":
    main()
